blank_issues_enabled: false
contact_links:
  - name: Krkn Community Support
    url: https://github.com/krkn-chaos/krkn/discussions
    about: Please ask and answer questions here.
  - name: Krkn Documentation
    url: https://krkn-chaos.github.io/krkn/
    about: Check the documentation for help.
